language: rust

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - libsodium-dev
    - pkg-config

script:
  - cargo test

branches:
  only:
    - master
