language: rust

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
    - libsodium 
    - openssl-sys
    - openssl
    - pkg-config

script:
  - cargo test

branches:
  only:
    - master
