language: rust

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y

script:
  - cat /etc/lsb-release 
  - cargo tesst

branches:
  only:
    - master
